version: '3'

services:
  db:
    image: mariadb:10
    hostname: mariadb-controlpage
    container_name: controlpage_mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=DYxH2NgFh7A55BEqUYAMGPxPxLv6fD3DeCa487LWMD
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    hostname: mariadb-controlpage-adminer
    container_name: controlpage_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mariadb_data:
