spring:
  datasource:
    url: jdbc:mysql://192.168.0.199:3306/controlpage
    username: ControlPageUser
    password: ^SCzJ&VkXzh97mdfW%8T
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  data:
    rest:
      default-media-type: application/json
  sql:
    init:
      platform: mysql

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

springdoc:
  api-docs:
    path: /api-docs
