spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/controlpage
    url: jdbc:mysql://${DB_HOST:localhost}:3306/controlpage
    username: ControlPageUser
    password: 6xovUH2QmUZooPTyYrpD9Js8fZRrMBrkqHzs4soRdP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  data:
    rest:
      default-media-type: application/json
  sql:
    init:
      platform: mysql

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

springdoc:
  api-docs:
    path: /api-docs
