package at.fischers.controlpagebackend.unit.entity;

import at.fischers.controlpagebackend.model.entity.ViewEntity;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

public class ViewEntityTest {
     /*
        Testing autogenerated constructors, getter/setter is pretty useless -> so just test custom equals
        (Because they are stored in a database two Views with the same id are considered equals)
     */

    @Test
    void testEquals() {
        assertEquals(new ViewEntity(42, "V1", null, null), new ViewEntity(42, "V2", null, null));
        assertNotEquals(new ViewEntity(1, "V1", null, null), new ViewEntity(2, "V1", null, null));
    }
}
