package eu.fischerserver.controlpage.controlpagebackend.unit.dto;

import eu.fischerserver.controlpage.controlpagebackend.model.domain.view.BasicView;
import eu.fischerserver.controlpage.controlpagebackend.model.domain.view.FullView;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

public class ViewTest {
    /*
        Testing autogenerated constructors, getter/setter is pretty useless -> so just test custom equals
        (Because they are stored in a database two Views with the same id are considered equals)
     */

    @Test
    void testEquals() {
        assertEquals(new BasicView(42, "V1", null), new BasicView(42, "V2", null));
        assertNotEquals(new BasicView(1, "V1", null), new BasicView(2, "V1", null));

        assertEquals(new FullView(42, "V1", null, null), new FullView(42, "V2", null, null));
        assertNotEquals(new FullView(1, "V1", null, null), new FullView(2, "V1", null, null));
    }
}
